---
layout: single
title: "📘[DRF] 예외처리를 데코레이터로?"
toc: true
toc_sticky: true
toc_label: "목차"
categories: django
excerpt: ""
tag: [python, drf]
---

# try ~ except 절을 데코레이터로 관리해보자!

프로젝트 진행 도중, `예외처리`로직을 따로 분리해서 관리하면 `view(or controller)`에서 반복적인 예외처리 로직이 필요 없어져 가독성이 좋아질거 같다는 피드백을 받았다!

그래서 django에서 데코레이터를 만들어, 해당 데코레이터를 통해 예외처리를 진행하도록 수정했다!

## 데코레이터를 만드는건 어떻게 할까?

우선, django에서 데코레이터를 만드는 방법부터 알아보자!

```python
from functools import wraps

def my_decorator(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        # 데코레이터가 하는 일
        result = func(*args, **kwargs)
        return result
    return wrapper
```

이렇게 작성하면, 다른 파일에서 `@my_decorator` 를 적어 데코레이터를 적용할 수 있다.

```python
@my_decorator
def say_hello(name):
    return f"Hello, {name}!"
   
   
print(say_hello("Alice"))  # "Calling function say_hello"와 "Hello, Alice!" 출력
print(say_hello.__name__)  # "say_hello" 출력
print(say_hello.__doc__)   # "Greet someone with their name." 출력
```

## 내가 적어본 데코레이터!

```python
def exception_handler(view: bool = False):
    def exception_handler_decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            try:
                return func(*args, **kwargs)
            except Card.DoesNotExist as e:
                print(f"An error occurred in {func.__name__}: {e}")
                return error_response("Invalid Card", status.HTTP_400_BAD_REQUEST)
            except Game.DoesNotExist as e:
                print(f"An error occuerd in {func.__name__}: {e}")
                return error_response("Invalid Game", status.HTTP_400_BAD_REQUEST)
            except Gametype.DoesNotExist as e:
                print(f"An error occurred in {func.__name__}: {e}")
                return error_response("Invalid Game Type", status.HTTP_400_BAD_REQUEST)
            except AIAnswer.DoesNotExist as e:
                print(f"An error occurred in {func.__name__}: {e}")
                return error_response("Invalid AI Answer", status.HTTP_400_BAD_REQUEST)
            except Exception as e:
                print(f"An error occurred in {func.__name__}: {e}")
                return error_response("Internal Server Error", status.HTTP_500_INTERNAL_SERVER_ERROR)
        return wrapper
    return exception_handler_decorator
```

- `def exception_handler(view: bool = False):`
    - views에서 사용할 데코레이터를 정의한다.
    - `view: bool = False`: 만약 이 데코레이터를 사용한 function이 view인지 아닌지 검사한다. 기본 값은 False
- `@wraps(func)`
    - Python에서 데코레이터를 정의할 때 사용하는 도구로, `functools` 모듈에서 제공된다.
    - 데코레이트된 함수가 원래 `함수의 이름`, `문서 문자열(docstring)`, `주석`, 및 `기타 속성`을 잃지 않도록 한다.
- `def wrapper(*args, **kwargs)`
    - `wrapper` 함수는 원래 함수(`func`)를 래핑하여 예외 처리를 추가한다.
    - `*args`와 `**kwargs`는 원래 함수의 모든 인자를 그대로 받는다.
    - 본격적인 예외처리 로직을 수행한다.
- `try ~ except`
    - `return func(*args, **kwargs)`: 원래 함수를 호출하고, 그 결과를 반환한다.
    - 이후에는 데이터 존재 여부의 예외처리와 그 외의 예외는 제네릭하게 받아 예외를 처리한다.

### 내가 만든 데코레이터에서 쓴 error_response는 뭐지?

```python
from rest_framework import status
from rest_framework.response import Response

def error_response(error: str, status_code: int):
    return Response({"error": error}, status_code)
```

- 인자로 `에러 메시지(error)`와 `HTTP 상태 코드(status_code)`를 받는다.
- 사용자에게는 `{"error": error}` 포멧의 에러 메시지를 보여주고, 상태 코드를 전달한다.

# 데코레이터 동작 순서?

하나의 동작(함수)을 수행할 때, 여러 가지의 데코레이터를 사용할 수 있다.

그런데, 여러 개의 데코레이터가 붙어있으면 이 데코레이터들이 어떤 순서를 갖고 동작하는지를 알아야 내가 데코레이터를 만들어 적절하게 쓸 수 있다!

![KakaoTalk_Photo_2024-06-13-03-45-18](https://github.com/TUK-3oon/hello-tarot-BE/assets/104587537/dd91591e-e94f-4ffb-b106-1d3e65a5be75)


위의 예시를 보면 이해가 쉽다!

함수가 먼저 실행되고, 위에 있는 데코레이터 → 그 위의 데코레이터 순으로 동작하게 된다.

이 포스팅에서 작성한 예시는 예외를 처리하는 데코레이터였으니, 함수가 동작하고 그 결과에 대한 예외처리를 바로 처리해야하므로, 함수 바로 위에 선언했다.